-- PHASE 34: ENTERPRISE FOUNDATION (SUPABASE READY)
-- KMK(T) National Church Portal

-- 1) OWNERSHIP + WORKFLOW + COMPLIANCE + VISITOR + AUDIT TABLES
create table if not exists public.level_ownership_assignments (
  id bigint generated by default as identity primary key,
  level_key text not null,
  level_name text not null,
  primary_owner uuid null,
  secondary_owner uuid null,
  reviewer uuid null,
  approver uuid null,
  submission_status text default 'not_submitted',
  approval_status text default 'pending',
  progress numeric default 0,
  assigned_date timestamptz null,
  last_submission timestamptz null,
  last_approval timestamptz null,
  is_locked boolean default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid null,
  updated_by uuid null,
  status text not null default 'active',
  is_archived boolean not null default false,
  archived_at timestamptz null,
  archived_by uuid null
);

create table if not exists public.workflow_records (
  id bigint generated by default as identity primary key,
  module_key text not null,
  level_key text not null,
  status text not null default 'draft',
  payload jsonb default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid null,
  updated_by uuid null,
  submitted_at timestamptz null,
  submitted_by uuid null,
  reviewed_at timestamptz null,
  reviewed_by uuid null,
  approved_at timestamptz null,
  approved_by uuid null,
  rejected_at timestamptz null,
  rejected_by uuid null,
  is_locked boolean not null default false,
  is_archived boolean not null default false,
  archived_at timestamptz null,
  archived_by uuid null
);

create table if not exists public.compliance_tracking_rows (
  id bigint generated by default as identity primary key,
  level_key text not null,
  area_name text not null,
  owner_user_id uuid null,
  required_sections int not null default 0,
  completed_sections int not null default 0,
  completion_percent numeric not null default 0,
  submission_status text default 'not_started',
  approval_status text default 'pending',
  missing_fields_count int default 0,
  missing_documents_count int default 0,
  deadline date null,
  status text default 'not_started',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid null,
  updated_by uuid null,
  is_archived boolean not null default false,
  archived_at timestamptz null,
  archived_by uuid null
);

create table if not exists public.report_center_jobs (
  id bigint generated by default as identity primary key,
  report_type text not null,
  format text not null,
  filters jsonb default '{}'::jsonb,
  generated_by uuid null,
  generated_at timestamptz not null default now(),
  status text default 'queued',
  file_url text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid null,
  updated_by uuid null,
  is_archived boolean not null default false,
  archived_at timestamptz null,
  archived_by uuid null
);

create table if not exists public.website_visitors (
  id bigint generated by default as identity primary key,
  actor_name text null,
  role text null,
  device_type text null,
  browser text null,
  ip_placeholder text null,
  location_placeholder text null,
  current_page text null,
  login_time timestamptz null,
  last_seen timestamptz null,
  session_duration_seconds int default 0,
  online_status text default 'offline',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid null,
  updated_by uuid null,
  status text default 'active',
  is_archived boolean not null default false,
  archived_at timestamptz null,
  archived_by uuid null
);

create table if not exists public.online_users (
  id bigint generated by default as identity primary key,
  user_id uuid null,
  role text null,
  current_page text null,
  last_seen timestamptz not null default now(),
  online_status text default 'online',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.session_activity_logs (
  id bigint generated by default as identity primary key,
  user_id uuid null,
  actor_name text null,
  role text null,
  action text not null,
  current_page text null,
  metadata jsonb default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid null,
  updated_by uuid null,
  status text default 'active',
  is_archived boolean not null default false,
  archived_at timestamptz null,
  archived_by uuid null
);

-- 2) FINANCE HARDENING (ADD UNIVERSAL AUDIT COLUMNS)
alter table if exists public.finance_transactions
  add column if not exists created_by uuid null,
  add column if not exists updated_by uuid null,
  add column if not exists is_archived boolean not null default false,
  add column if not exists archived_at timestamptz null,
  add column if not exists archived_by uuid null;

alter table if exists public.finance_budgets
  add column if not exists created_by uuid null,
  add column if not exists updated_by uuid null,
  add column if not exists is_archived boolean not null default false,
  add column if not exists archived_at timestamptz null,
  add column if not exists archived_by uuid null;

alter table if exists public.finance_approvals
  add column if not exists created_by uuid null,
  add column if not exists updated_by uuid null,
  add column if not exists is_archived boolean not null default false,
  add column if not exists archived_at timestamptz null,
  add column if not exists archived_by uuid null;

-- 3) ENABLE RLS
alter table if exists public.level_ownership_assignments enable row level security;
alter table if exists public.workflow_records enable row level security;
alter table if exists public.compliance_tracking_rows enable row level security;
alter table if exists public.report_center_jobs enable row level security;
alter table if exists public.website_visitors enable row level security;
alter table if exists public.online_users enable row level security;
alter table if exists public.session_activity_logs enable row level security;

-- 4) BASE POLICIES (replace with exact role model in production)
drop policy if exists "ownership_select_authenticated" on public.level_ownership_assignments;
create policy "ownership_select_authenticated"
on public.level_ownership_assignments
for select
to authenticated
using (true);

drop policy if exists "workflow_select_authenticated" on public.workflow_records;
create policy "workflow_select_authenticated"
on public.workflow_records
for select
to authenticated
using (true);

drop policy if exists "workflow_write_admin" on public.workflow_records;
create policy "workflow_write_admin"
on public.workflow_records
for all
to authenticated
using (true)
with check (true);

-- 5) REALTIME PUBLICATION SUPPORT (idempotent)
do $$
begin
  begin
    alter publication supabase_realtime add table public.workflow_records;
  exception when duplicate_object then null;
  end;
  begin
    alter publication supabase_realtime add table public.level_ownership_assignments;
  exception when duplicate_object then null;
  end;
  begin
    alter publication supabase_realtime add table public.compliance_tracking_rows;
  exception when duplicate_object then null;
  end;
  begin
    alter publication supabase_realtime add table public.finance_transactions;
  exception when duplicate_object then null;
  end;
  begin
    alter publication supabase_realtime add table public.website_visitors;
  exception when duplicate_object then null;
  end;
end $$;
