-- PHASE 35: LEADERSHIP SUITE TABLES (SUPABASE READY)
-- KMK(T) NATIONAL CHURCH PORTAL

create table if not exists public.national_leadership_positions (
  id bigint generated by default as identity primary key,
  position_name text not null,
  category text null,
  executive_cluster text null,
  status text default 'active',
  approval_status text default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid null,
  updated_by uuid null,
  is_archived boolean not null default false,
  archived_at timestamptz null,
  archived_by uuid null
);

create table if not exists public.national_leaders (
  id bigint generated by default as identity primary key,
  full_name text not null,
  role_name text not null,
  leader_type text not null default 'NGAZI_KUU',
  phone text null,
  email text null,
  dayosisi text null,
  jimbo text null,
  tawi text null,
  service_start_date date null,
  end_of_term date null,
  profile_status text default 'incomplete',
  status text default 'draft',
  approval_status text default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid null,
  updated_by uuid null,
  is_archived boolean not null default false,
  archived_at timestamptz null,
  archived_by uuid null
);

create table if not exists public.diocese_leadership_positions (like public.national_leadership_positions including defaults);
create table if not exists public.diocese_leaders (like public.national_leaders including defaults);
create table if not exists public.bishops (like public.national_leaders including defaults);
create table if not exists public.pastors (like public.national_leaders including defaults);
create table if not exists public.evangelists (like public.national_leaders including defaults);
create table if not exists public.elders (like public.national_leaders including defaults);
create table if not exists public.deacons (like public.national_leaders including defaults);
create table if not exists public.local_leaders (like public.national_leaders including defaults);
create table if not exists public.leader_assignments (like public.national_leaders including defaults);
create table if not exists public.leader_transfers (like public.national_leaders including defaults);
create table if not exists public.leader_documents (like public.national_leaders including defaults);
create table if not exists public.leader_history (like public.national_leaders including defaults);
create table if not exists public.leader_approvals (like public.national_leaders including defaults);
create table if not exists public.leader_visibility_rules (like public.national_leaders including defaults);
create table if not exists public.leader_notes (like public.national_leaders including defaults);
create table if not exists public.leader_tags (like public.national_leaders including defaults);
create table if not exists public.vacancies (like public.national_leaders including defaults);

alter table if exists public.national_leadership_positions enable row level security;
alter table if exists public.national_leaders enable row level security;
