-- PHASE 36: WAUMINI & FAMILIA SUPABASE FOUNDATION

create table if not exists public.members (
  id bigint generated by default as identity primary key,
  full_name text not null,
  gender text null,
  dob date null,
  age int null,
  phone text null,
  email text null,
  dayosisi text null,
  jimbo text null,
  branch text null,
  membership_category text null,
  member_type text null,
  baptism_status text null,
  catechism_status text null,
  profile_status text default 'Incomplete',
  status text default 'Draft',
  approval_status text default 'Draft',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid null,
  updated_by uuid null,
  is_archived boolean not null default false,
  archived_at timestamptz null,
  archived_by uuid null
);

create table if not exists public.families (like public.members including defaults);
create table if not exists public.family_members (like public.members including defaults);
create table if not exists public.baptism_records (like public.members including defaults);
create table if not exists public.catechism_records (like public.members including defaults);
create table if not exists public.member_talents (like public.members including defaults);
create table if not exists public.member_documents (like public.members including defaults);
create table if not exists public.member_transfers (like public.members including defaults);
create table if not exists public.member_approvals (like public.members including defaults);
create table if not exists public.member_notes (like public.members including defaults);
create table if not exists public.member_audit_logs (like public.members including defaults);

alter table if exists public.members enable row level security;
alter table if exists public.families enable row level security;
alter table if exists public.family_members enable row level security;
alter table if exists public.baptism_records enable row level security;
alter table if exists public.catechism_records enable row level security;
alter table if exists public.member_talents enable row level security;
alter table if exists public.member_documents enable row level security;
alter table if exists public.member_transfers enable row level security;
alter table if exists public.member_approvals enable row level security;
alter table if exists public.member_notes enable row level security;
alter table if exists public.member_audit_logs enable row level security;
