-- Phase 9.5a: Worship Attendance & Offerings records (Supabase)

create extension if not exists pgcrypto;

-- Helper claims readers (safe defaults)
create or replace function public.current_app_role()
returns text
language sql
stable
as $$
  select coalesce((auth.jwt() ->> 'app_role')::text, 'member')
$$;

create or replace function public.current_dayosisi()
returns text
language sql
stable
as $$
  select coalesce((auth.jwt() ->> 'dayosisi')::text, '')
$$;

create or replace function public.current_tawi()
returns text
language sql
stable
as $$
  select coalesce((auth.jwt() ->> 'tawi')::text, '')
$$;

create table if not exists public.worship_service_records (
  id bigint generated by default as identity primary key,
  tarehe date not null,
  dayosisi text not null,
  jimbo text not null,
  tawi text not null,
  aina_ya_ibada text not null,
  ibada_1 integer not null default 0 check (ibada_1 >= 0),
  ibada_2 integer not null default 0 check (ibada_2 >= 0),
  jumla_mahudhurio integer not null default 0 check (jumla_mahudhurio >= 0),
  jumla_mapato bigint not null default 0 check (jumla_mapato >= 0),
  salio_jipya bigint not null default 0,
  mhubiri text not null default '',
  approval_status text not null default 'Draft',
  created_by text not null default 'SYSTEM',
  last_updated text not null default to_char(now(), 'YYYY-MM-DD HH24:MI'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_worship_records_tarehe on public.worship_service_records (tarehe desc);
create index if not exists idx_worship_records_dayosisi on public.worship_service_records (dayosisi);
create index if not exists idx_worship_records_tawi on public.worship_service_records (tawi);
create index if not exists idx_worship_records_approval_status on public.worship_service_records (approval_status);

-- Keep updated_at fresh
create or replace function public.touch_worship_service_records_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_touch_worship_service_records_updated_at on public.worship_service_records;
create trigger trg_touch_worship_service_records_updated_at
before update on public.worship_service_records
for each row
execute function public.touch_worship_service_records_updated_at();

-- Data API table access (still protected by RLS below)
grant select, insert, update, delete on table public.worship_service_records to authenticated;
grant usage, select on sequence public.worship_service_records_id_seq to authenticated;

alter table public.worship_service_records enable row level security;

drop policy if exists "worship_records_select_policy" on public.worship_service_records;
create policy "worship_records_select_policy"
on public.worship_service_records
for select
to authenticated
using (
  public.current_app_role() in ('super_admin', 'admin')
  or (public.current_app_role() = 'askofu_dayosisi' and dayosisi = public.current_dayosisi())
  or (public.current_app_role() in ('mchungaji', 'secretary', 'treasurer', 'branch_leader') and tawi = public.current_tawi())
);

drop policy if exists "worship_records_insert_policy" on public.worship_service_records;
create policy "worship_records_insert_policy"
on public.worship_service_records
for insert
to authenticated
with check (
  public.current_app_role() in ('super_admin', 'admin')
  or (public.current_app_role() = 'askofu_dayosisi' and dayosisi = public.current_dayosisi())
  or (public.current_app_role() in ('mchungaji', 'secretary', 'treasurer', 'branch_leader') and tawi = public.current_tawi())
);

drop policy if exists "worship_records_update_policy" on public.worship_service_records;
create policy "worship_records_update_policy"
on public.worship_service_records
for update
to authenticated
using (
  public.current_app_role() in ('super_admin', 'admin')
  or (public.current_app_role() = 'askofu_dayosisi' and dayosisi = public.current_dayosisi())
  or (public.current_app_role() in ('mchungaji', 'secretary', 'treasurer', 'branch_leader') and tawi = public.current_tawi())
)
with check (
  public.current_app_role() in ('super_admin', 'admin')
  or (public.current_app_role() = 'askofu_dayosisi' and dayosisi = public.current_dayosisi())
  or (public.current_app_role() in ('mchungaji', 'secretary', 'treasurer', 'branch_leader') and tawi = public.current_tawi())
);

drop policy if exists "worship_records_delete_policy" on public.worship_service_records;
create policy "worship_records_delete_policy"
on public.worship_service_records
for delete
to authenticated
using (
  public.current_app_role() in ('super_admin', 'admin')
  or (public.current_app_role() = 'askofu_dayosisi' and dayosisi = public.current_dayosisi())
  or (public.current_app_role() in ('mchungaji', 'secretary') and tawi = public.current_tawi())
);
