-- STEP 16: Master Settings Center

create table if not exists public.master_settings_center (
  id uuid primary key default gen_random_uuid(),
  official_name text not null default 'KMK(T) Portal',
  motto text not null default '',
  logo_url text not null default '',
  favicon_url text not null default '',
  primary_color text not null default '#0B1F3A',
  secondary_color text not null default '#123C69',
  accent_color text not null default '#D4AF37',
  footer_text text not null default 'KMK(T) Tanzania',
  signature_name text not null default '',
  signature_title text not null default '',
  pdf_header_text text not null default 'KMK(T) Official Report',
  pdf_footer_text text not null default 'Generated by KMK(T) Portal',
  excel_header_text text not null default 'KMK(T) Export',
  print_header_text text not null default 'KMK(T) Print Layout',
  email_templates jsonb not null default '{}'::jsonb,
  sms_templates jsonb not null default '{}'::jsonb,
  language text not null default 'sw',
  timezone text not null default 'Africa/Dar_es_Salaam',
  default_dashboard_settings jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.portal_touch_master_settings_center()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_master_settings_center_touch on public.master_settings_center;
create trigger trg_master_settings_center_touch
before update on public.master_settings_center
for each row
execute function public.portal_touch_master_settings_center();

alter table public.master_settings_center enable row level security;

drop policy if exists master_settings_center_select on public.master_settings_center;
create policy master_settings_center_select
on public.master_settings_center
for select
to authenticated
using (
  public.current_app_role() in (
    'super_admin',
    'chief_admin',
    'national_admin',
    'office_admin'
  )
);

drop policy if exists master_settings_center_insert_super_admin on public.master_settings_center;
create policy master_settings_center_insert_super_admin
on public.master_settings_center
for insert
to authenticated
with check (public.current_app_role() = 'super_admin');

drop policy if exists master_settings_center_update_super_admin on public.master_settings_center;
create policy master_settings_center_update_super_admin
on public.master_settings_center
for update
to authenticated
using (public.current_app_role() = 'super_admin')
with check (public.current_app_role() = 'super_admin');
