/**
 * Jedwali zinazotegemewa na `portal-global-live-sync` (AppLayout).
 * Orodha wazi (si schema wildcard) — inalingana na `supabase_realtime` publication na huzuia usajili usiofaa.
 */
export const PORTAL_GLOBAL_REALTIME_TABLES: readonly string[] = [
  "church_members",
  "church_families",
  "dayosisi",
  "audit_logs",
  "portal_directory_profiles",
  "portal_visibility_rules",
  "portal_module_matrix",
  "church_jimbo",
  "church_tawi",
  "church_finance_entries",
  "church_income_sources",
  "church_income_lines",
  "church_viongozi",
  "national_leadership_profiles",
  "portal_domain_entities",
  "events",
  "gallery",
  "news_posts",
  "documents",
  "videos",
  "audios",
  "sermons",
  "attendance_sessions",
  "attendance_records",
  "file_manager_items",
  "notifications",
  "notification_reads",
  "system_alerts",
  "site_settings",
  "about_kmkt",
  "live_streams",
  "communications",
  "developer_profile",
  "church_structure_entities",
  "church_structure_leaders",
  "portal_branch_engine_workspace",
  "portal_project_notes",
  "aid_requests",
  "aid_beneficiaries",
  "aid_disbursements",
] as const;
